# Intro to Numpy

# 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.16.2


# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a=np.random.random((2, 3, 5))
a1=np.random.rand(2, 3, 5)
a2=np.random.randint(10 ,size=(2, 3, 5))
a3=np.random.sample((2, 3, 5))

# 4. Print a.

In [4]:
print (a)       # elementos aleatorios entre 0 y 1
print (a1)      # elementos aleatorios entre 0 y 1
print (a2)      # elementos aleatorios enteros entre 0 y 10
print (a3)      # elementos aleatorios entre 0 y 1

[[[0.92908285 0.08738185 0.63700285 0.85827313 0.70112754]
  [0.66479305 0.08173102 0.38185062 0.06250517 0.70014753]
  [0.74279749 0.22003722 0.24296835 0.30920813 0.53224183]]

 [[0.90241464 0.36361518 0.64325267 0.27904856 0.78588251]
  [0.65242106 0.0582239  0.11352888 0.433698   0.14107852]
  [0.86403796 0.69861859 0.98393144 0.38780823 0.16879465]]]
[[[5.53793667e-01 6.49733000e-01 1.81812134e-01 1.46867277e-01
   5.13380439e-01]
  [5.55523184e-01 4.37292059e-01 3.69436330e-01 6.08076262e-01
   1.62386561e-02]
  [4.05122559e-02 4.79121528e-02 6.23085281e-02 3.29478130e-02
   5.59117224e-01]]

 [[9.96843468e-01 5.02034762e-01 1.02186681e-01 3.07545382e-01
   1.00483833e-01]
  [5.41361219e-01 9.53404701e-01 2.68010120e-01 1.62658500e-01
   5.02712362e-01]
  [7.27075828e-01 4.42592725e-01 8.40544140e-01 6.22823620e-01
   7.23973855e-04]]]
[[[2 9 2 6 3]
  [0 5 4 1 0]
  [3 2 7 2 4]]

 [[2 0 8 9 4]
  [6 9 4 9 1]
  [5 8 0 6 1]]]
[[[0.93491192 0.29560842 0.12990755 0.73823351 0.8151247 ]

# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [5]:
b=np.ones((5, 2, 3))

# 6. Print b.

In [6]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
if a.size==b.size:
    print (True)
# ambos tienen el mismo tamaño

True


# 8. Are you able to add a and b? Why or why not?

In [8]:
print (np.add(a, b))
# no se puede porque a y b no tienen las mismas dimensiones

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
c=b.transpose(1, 2, 0)
print (c.shape)

(2, 3, 5)


# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [10]:
d=np.add(a,c)
print (d.shape)
# al transponer ya tienen la misma dimension y se pueden sumar

(2, 3, 5)


# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print ('a')
print (a)
print ('')
print ('')
print ('d')
print (d)
# se ha sumado 1 a todos los elementos de la matriz a y resulta d

a
[[[0.92908285 0.08738185 0.63700285 0.85827313 0.70112754]
  [0.66479305 0.08173102 0.38185062 0.06250517 0.70014753]
  [0.74279749 0.22003722 0.24296835 0.30920813 0.53224183]]

 [[0.90241464 0.36361518 0.64325267 0.27904856 0.78588251]
  [0.65242106 0.0582239  0.11352888 0.433698   0.14107852]
  [0.86403796 0.69861859 0.98393144 0.38780823 0.16879465]]]


d
[[[1.92908285 1.08738185 1.63700285 1.85827313 1.70112754]
  [1.66479305 1.08173102 1.38185062 1.06250517 1.70014753]
  [1.74279749 1.22003722 1.24296835 1.30920813 1.53224183]]

 [[1.90241464 1.36361518 1.64325267 1.27904856 1.78588251]
  [1.65242106 1.0582239  1.11352888 1.433698   1.14107852]
  [1.86403796 1.69861859 1.98393144 1.38780823 1.16879465]]]


# 12. Multiply a and c. Assign the result to e.

In [12]:
e=np.multiply(a, c)
print (e)

[[[0.92908285 0.08738185 0.63700285 0.85827313 0.70112754]
  [0.66479305 0.08173102 0.38185062 0.06250517 0.70014753]
  [0.74279749 0.22003722 0.24296835 0.30920813 0.53224183]]

 [[0.90241464 0.36361518 0.64325267 0.27904856 0.78588251]
  [0.65242106 0.0582239  0.11352888 0.433698   0.14107852]
  [0.86403796 0.69861859 0.98393144 0.38780823 0.16879465]]]


# 13. Does e equal to a? Why or why not?

In [13]:
print (e==a)
# la matriz a y la matriz e son iguales porque el producto elemento a elemento es con c, 
# que es una matriz con todos los elementos igual a  1

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [14]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print (d_max)
print (d_min)
print (d_mean)

1.9839314404963921
1.058223900064513
1.487583446830883


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
f=np.empty((2, 3, 5))
print (f)
# empty no significa vacio, significa que no inicializa elementos

[[[0.92908285 0.08738185 0.63700285 0.85827313 0.70112754]
  [0.66479305 0.08173102 0.38185062 0.06250517 0.70014753]
  [0.74279749 0.22003722 0.24296835 0.30920813 0.53224183]]

 [[0.90241464 0.36361518 0.64325267 0.27904856 0.78588251]
  [0.65242106 0.0582239  0.11352888 0.433698   0.14107852]
  [0.86403796 0.69861859 0.98393144 0.38780823 0.16879465]]]


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [16]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min==d[i][j][k]:
                f[i][j][k]=0
            elif d_min<d[i][j][k] and d[i][j][k]<d_mean:
                f[i][j][k]=25
            elif d_mean==d[i][j][k]:
                f[i][j][k]=50
            elif d_mean<d[i][j][k] and d[i][j][k]<d_max:
                f[i][j][k]=75
            elif d[i][j][k]==d_max:
                f[i][j][k]=100

#print (d)
print (f)
# si, correcto

[[[ 75.  25.  75.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75.   0.  25.  25.  25.]
  [ 75.  75. 100.  25.  25.]]]


# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

In [17]:

f=np.ndarray.astype(f, dtype=str)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min==d[i][j][k]:
                f[i][j][k]="A"
            elif d_min<d[i][j][k] and d[i][j][k]<d_mean:
                f[i][j][k]="B"
            elif d_mean==d[i][j][k]:
                f[i][j][k]="C"
            elif d_mean<d[i][j][k] and d[i][j][k]<d_max:
                f[i][j][k]="D"
            elif d[i][j][k]==d_max:
                f[i][j][k]="E"

print (f)



[[['D' 'B' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']]

 [['D' 'B' 'D' 'B' 'D']
  ['D' 'A' 'B' 'B' 'B']
  ['D' 'D' 'E' 'B' 'B']]]
