# Numpy

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Why-numpy" data-toc-modified-id="Why-numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Why numpy</a></span></li><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating arrays</a></span><ul class="toc-item"><li><span><a href="#Custom" data-toc-modified-id="Custom-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Custom</a></span><ul class="toc-item"><li><span><a href="#1-dimensional" data-toc-modified-id="1-dimensional-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>1 dimensional</a></span></li><li><span><a href="#2-dimensional" data-toc-modified-id="2-dimensional-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>2 dimensional</a></span></li><li><span><a href="#3-dimensional" data-toc-modified-id="3-dimensional-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>3 dimensional</a></span></li></ul></li><li><span><a href="#Built-in" data-toc-modified-id="Built-in-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Built-in</a></span><ul class="toc-item"><li><span><a href="#arange" data-toc-modified-id="arange-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span><code>arange</code></a></span></li><li><span><a href="#linspace" data-toc-modified-id="linspace-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span><code>linspace</code></a></span></li></ul></li></ul></li><li><span><a href="#Properties" data-toc-modified-id="Properties-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Properties</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Slicing</a></span><ul class="toc-item"><li><span><a href="#Conditional-slicing" data-toc-modified-id="Conditional-slicing-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Conditional slicing</a></span></li></ul></li><li><span><a href="#Useful-array-methods" data-toc-modified-id="Useful-array-methods-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Useful array methods</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Further materials</a></span></li></ul></div>

In [1]:
import numpy as np

Convention for this notebook:
 - `a` will always be a 1-dimensional array.
 - `b` will always be a 2-dimensional array.
 - `c` will always be a 3-dimensional array.

## Why numpy

NumPy (numerical Python) is used to do numerical computations efficiently in Python

In [2]:
lst = [1, 2, 3, 4, 5]

In [3]:
type(lst)

list

I want to multiply all elements by `2`

In [4]:
lst * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Did not work

`np.array` is the function

`arr` is the variable name. We are free to choose it

In [5]:
arr = np.array(lst)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr * 2

array([ 2,  4,  6,  8, 10])

As expected

In [9]:
arr * 1.5

array([1.5, 3. , 4.5, 6. , 7.5])

In [10]:
lst * 1.5

TypeError: can't multiply sequence by non-int of type 'float'

Takes less time to do stuff, C programming language optimized

In [11]:
lst2 = list(range(1_000_000))

In [12]:
type(lst2)

list

In [13]:
lst2[:20]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [14]:
%%timeit
list(map(lambda x: x * 2, lst2))

140 ms ± 647 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
%%timeit
doubles = [n * 2 for n in lst2]

84.4 ms ± 912 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
arr2 = np.array(lst2)

In [17]:
type(arr2)

numpy.ndarray

In [18]:
%%timeit
doubles = arr2 * 2

1.76 ms ± 67 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Creating arrays

### Custom

#### 1 dimensional

In [19]:
a = np.array([1, 2, 3])

In [20]:
type(a)

numpy.ndarray

In [21]:
a

array([1, 2, 3])

In [22]:
a.shape

(3,)

#### 2 dimensional

In [23]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b.shape

(2, 3)

Meaning 2 rows, 3 columns.

In [26]:
b2 = np.array([[1, 2, 3], [4, 5, 6, 7]])

<ipython-input-26-c25226e2f92c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  b2 = np.array([[1, 2, 3], [4, 5, 6, 7]])


In [27]:
b2

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

#### 3 dimensional

In [28]:
c = np.array([
    [[55, 66, 3], [40, 90, 3]],
    [[10, 10, 3], [10, 11, 3]],
    [[8, 9, 354], [6, 75, 34]],
    [[2, 3, 443], [3, 4, 199]]
])

In [29]:
c

array([[[ 55,  66,   3],
        [ 40,  90,   3]],

       [[ 10,  10,   3],
        [ 10,  11,   3]],

       [[  8,   9, 354],
        [  6,  75,  34]],

       [[  2,   3, 443],
        [  3,   4, 199]]])

In [30]:
c.shape

(4, 2, 3)

Example 3 dimensional arrays: RGB images

### Built-in

In [31]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.zeros((3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((2, 3)) * 4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.full((2, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [38]:
np.empty((2, 3))

array([[0.000000e+000, 4.940656e-324, 9.881313e-324],
       [4.940642e-318, 4.940647e-318, 4.940652e-318]])

In [39]:
np.random

<module 'numpy.random' from '/home/sheriff/miniconda3/envs/ironhack/lib/python3.8/site-packages/numpy/random/__init__.py'>

In [40]:
np.random.random

<function RandomState.random>

In [41]:
# uniform
np.random.random()

0.9342797314044686

In [42]:
count = 0

for i in range(1000):
    if np.random.random() > 0.1:
        count += 1

In [43]:
count

893

In [44]:
np.random.randint(low=20, high=30, size=20)

array([20, 25, 24, 23, 22, 23, 22, 27, 26, 24, 26, 27, 20, 20, 29, 20, 20,
       26, 28, 22])

In [45]:
np.random.randint(low=20, high=30, size=(2, 3))

array([[25, 21, 20],
       [22, 23, 25]])

In [46]:
np.random.randn(10)

array([-0.79399151, -0.83921339,  1.20710801,  0.9747912 ,  1.12096684,
       -2.1658476 , -0.11769068, -0.37653159,  1.18059433,  0.15299577])

In [47]:
np.random.randn(3, 3)

array([[-1.03249506, -1.67047117,  1.47328538],
       [-2.05783111,  0.24451302, -1.09055996],
       [ 0.68903342, -0.44447143, -0.99463728]])

#### `arange`

Similar to `range`

In [48]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### `linspace`

In [49]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [50]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [51]:
np.linspace(0, 4, 5)

array([0., 1., 2., 3., 4.])

In [52]:
np.linspace(0, 4, 6)

array([0. , 0.8, 1.6, 2.4, 3.2, 4. ])

## Properties

In [53]:
b = np.random.randint(0, 100, (3, 4))

In [54]:
b

array([[28, 21, 13,  9],
       [73, 82,  2, 75],
       [86, 20, 69,  7]])

In [55]:
b.shape

(3, 4)

In [56]:
b

array([[28, 21, 13,  9],
       [73, 82,  2, 75],
       [86, 20, 69,  7]])

In [57]:
b.size

12

In [58]:
b.ndim

2

In [59]:
c

array([[[ 55,  66,   3],
        [ 40,  90,   3]],

       [[ 10,  10,   3],
        [ 10,  11,   3]],

       [[  8,   9, 354],
        [  6,  75,  34]],

       [[  2,   3, 443],
        [  3,   4, 199]]])

In [60]:
c.ndim

3

In [61]:
b.dtype

dtype('int64')

## Slicing

In [62]:
b = np.random.randint(0, 100, (3, 4))

In [63]:
b

array([[ 7, 16, 39, 50],
       [97, 22, 82, 40],
       [37, 31, 29, 88]])

In [64]:
b[0, 1]

16

In [65]:
b[2, 1]

31

In [66]:
b[0, :]

array([ 7, 16, 39, 50])

In [67]:
b[0, 1:3]

array([16, 39])

In [68]:
b[:, 0]

array([ 7, 97, 37])

In [69]:
b[1:3, 0:2]

array([[97, 22],
       [37, 31]])

In [70]:
b[1:, 0:2]

array([[97, 22],
       [37, 31]])

In [71]:
b[:,-1]

array([50, 40, 88])

In [72]:
b[1:3, 0:2].shape

(2, 2)

In [73]:
a = np.random.randint(0, 100, 20)

In [74]:
a

array([76, 52, 63, 75, 80, 30, 17, 77, 65, 23, 56, 71, 14, 31, 59,  4,  3,
       20, 90,  5])

In [75]:
a[0:10:3]

array([76, 75, 17, 23])

### Conditional slicing

In [76]:
a = np.random.randint(0, 100, 20)

In [77]:
a

array([71, 96, 15, 58,  3, 80, 85, 40, 66, 97, 42,  2, 19, 33, 60, 83, 15,
       30, 68, 31])

In [78]:
a.shape

(20,)

In [79]:
cond = (a > 10) & (a % 2 == 0)

In [80]:
cond

array([False,  True, False,  True, False,  True, False,  True,  True,
       False,  True, False, False, False,  True, False, False,  True,
        True, False])

In [81]:
cond.shape

(20,)

In [82]:
cond.sum()

9

In [83]:
a[3]

58

In [84]:
a[cond]

array([96, 58, 80, 40, 66, 42, 60, 30, 68])

**Exercise**: get the subarray of `a` of elements that start with `7`

In [85]:
cond = (a >= 70) & (a < 80) | (a == 7)

In [86]:
a[cond]

array([71])

In [87]:
cond = a // 10 == 7 

In [88]:
a[cond]

array([71])

Not ideal solutions. There does not exist one (I think)

**Exercise**: how many families have more than 2 children?

In [89]:
childrens = np.random.randint(0, 5, 100)

In [90]:
childrens

array([1, 2, 3, 1, 3, 3, 0, 3, 0, 4, 2, 4, 4, 3, 1, 2, 0, 4, 3, 3, 2, 2,
       0, 1, 4, 0, 3, 1, 0, 3, 4, 2, 1, 0, 3, 4, 2, 1, 1, 3, 2, 4, 4, 2,
       0, 1, 0, 4, 4, 0, 2, 0, 2, 0, 1, 2, 2, 3, 4, 1, 2, 0, 1, 4, 3, 1,
       1, 0, 3, 1, 0, 1, 0, 2, 1, 3, 0, 0, 2, 1, 3, 1, 3, 2, 4, 2, 4, 4,
       2, 2, 4, 1, 2, 3, 4, 1, 3, 2, 4, 0])

In [91]:
(childrens > 2).sum()

38

Conditional assignation

In [92]:
b = np.random.randint(0, 100, (3, 4))

In [93]:
b

array([[30, 47, 39, 38],
       [67, 82, 93,  6],
       [35, 83,  1, 39]])

In [94]:
b < 50

array([[ True,  True,  True,  True],
       [False, False, False,  True],
       [ True, False,  True,  True]])

In [95]:
b[b < 50] = 0

In [96]:
b[b > 90] = 100

In [97]:
b

array([[  0,   0,   0,   0],
       [ 67,  82, 100,   0],
       [  0,  83,   0,   0]])

Reminder: use `&` for "and" and `|` for "or" in numpy

## Useful array methods

In [98]:
a = np.random.randint(0, 1000, 30)

In [99]:
a

array([991, 509, 107, 568, 137, 912, 887, 507, 424, 347, 588, 687, 643,
       563, 780, 768, 465, 601, 168, 714, 389, 887, 172, 950,  49, 794,
       592, 101, 233, 884])

In [100]:
type(a)

numpy.ndarray

In [101]:
a.max()

991

In [102]:
a.min()

49

In [103]:
a.sum()

16417

In [104]:
b = np.random.randint(0, 1000, (4, 5))

In [105]:
b

array([[510, 140, 972, 200,  20],
       [436,  48, 310, 369, 956],
       [ 18, 971, 418, 418,   4],
       [690, 799,   0,  63, 106]])

In [106]:
b.max()

972

In [107]:
b.max(axis=1)

array([972, 956, 971, 799])

In [108]:
b.max(axis=0)

array([690, 971, 972, 418, 956])

In [109]:
a.mean()

547.2333333333333

In [110]:
b.mean(axis=0)

array([413.5, 489.5, 425. , 262.5, 271.5])

In [111]:
b.mean(axis=1)

array([368.4, 423.8, 365.8, 331.6])

In [112]:
a

array([991, 509, 107, 568, 137, 912, 887, 507, 424, 347, 588, 687, 643,
       563, 780, 768, 465, 601, 168, 714, 389, 887, 172, 950,  49, 794,
       592, 101, 233, 884])

In [113]:
a.mean()

547.2333333333333

In [114]:
a.var()

78234.77888888889

In [115]:
a.std()

279.70480669607537

In [116]:
b.var(axis=0)

array([ 60672.75, 161176.25, 123277.  ,  19807.25, 157684.75])

In [117]:
a = np.random.random(20)

In [118]:
a

array([0.67842195, 0.31712659, 0.80091973, 0.6824061 , 0.45544473,
       0.01874192, 0.79644313, 0.29870151, 0.79278963, 0.32662735,
       0.32532905, 0.62410807, 0.37090169, 0.85293753, 0.14474869,
       0.45065084, 0.63642128, 0.62566811, 0.82996172, 0.32944002])

In [119]:
a.round(1)

array([0.7, 0.3, 0.8, 0.7, 0.5, 0. , 0.8, 0.3, 0.8, 0.3, 0.3, 0.6, 0.4,
       0.9, 0.1, 0.5, 0.6, 0.6, 0.8, 0.3])

In [120]:
a.round(decimals=1)

array([0.7, 0.3, 0.8, 0.7, 0.5, 0. , 0.8, 0.3, 0.8, 0.3, 0.3, 0.6, 0.4,
       0.9, 0.1, 0.5, 0.6, 0.6, 0.8, 0.3])

In [121]:
a.round(2)

array([0.68, 0.32, 0.8 , 0.68, 0.46, 0.02, 0.8 , 0.3 , 0.79, 0.33, 0.33,
       0.62, 0.37, 0.85, 0.14, 0.45, 0.64, 0.63, 0.83, 0.33])

In [122]:
b

array([[510, 140, 972, 200,  20],
       [436,  48, 310, 369, 956],
       [ 18, 971, 418, 418,   4],
       [690, 799,   0,  63, 106]])

In [123]:
b.shape

(4, 5)

In [124]:
# turn to 1D array
b.flatten()

array([510, 140, 972, 200,  20, 436,  48, 310, 369, 956,  18, 971, 418,
       418,   4, 690, 799,   0,  63, 106])

In [125]:
b.reshape((3, 3))

ValueError: cannot reshape array of size 20 into shape (3,3)

In [126]:
b.reshape((5, 4))

array([[510, 140, 972, 200],
       [ 20, 436,  48, 310],
       [369, 956,  18, 971],
       [418, 418,   4, 690],
       [799,   0,  63, 106]])

In [127]:
b.reshape((10, 2))

array([[510, 140],
       [972, 200],
       [ 20, 436],
       [ 48, 310],
       [369, 956],
       [ 18, 971],
       [418, 418],
       [  4, 690],
       [799,   0],
       [ 63, 106]])

In [128]:
b

array([[510, 140, 972, 200,  20],
       [436,  48, 310, 369, 956],
       [ 18, 971, 418, 418,   4],
       [690, 799,   0,  63, 106]])

In [129]:
b.shape

(4, 5)

In [130]:
b.transpose()

array([[510, 436,  18, 690],
       [140,  48, 971, 799],
       [972, 310, 418,   0],
       [200, 369, 418,  63],
       [ 20, 956,   4, 106]])

In [131]:
b.transpose().shape

(5, 4)

In [132]:
b = np.random.randint(0, 100, (3, 3))

In [133]:
b

array([[97, 33, 39],
       [30, 49, 31],
       [ 3, 50, 73]])

In [134]:
b / 2

array([[48.5, 16.5, 19.5],
       [15. , 24.5, 15.5],
       [ 1.5, 25. , 36.5]])

In [135]:
1 / b

array([[0.01030928, 0.03030303, 0.02564103],
       [0.03333333, 0.02040816, 0.03225806],
       [0.33333333, 0.02      , 0.01369863]])

In [136]:
# inverse of a matrix
b_inv = np.linalg.inv(b)

In [137]:
b_inv

array([[ 0.01124955, -0.00254738, -0.00492827],
       [-0.01163804,  0.03864917, -0.01019508],
       [ 0.00750895, -0.02636734,  0.02088409]])

In [138]:
# matrix or vector multiplication
np.dot(b, b_inv).round(3)

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [-0.,  0.,  1.]])

In [139]:
b = np.random.randint(0, 10, (3, 3))

In [140]:
b

array([[3, 1, 8],
       [2, 8, 5],
       [4, 1, 6]])

In [141]:
b + b

array([[ 6,  2, 16],
       [ 4, 16, 10],
       [ 8,  2, 12]])

In [142]:
b * 3

array([[ 9,  3, 24],
       [ 6, 24, 15],
       [12,  3, 18]])

In [143]:
b ** 2

array([[ 9,  1, 64],
       [ 4, 64, 25],
       [16,  1, 36]])

In [144]:
np.exp(b)

array([[2.00855369e+01, 2.71828183e+00, 2.98095799e+03],
       [7.38905610e+00, 2.98095799e+03, 1.48413159e+02],
       [5.45981500e+01, 2.71828183e+00, 4.03428793e+02]])

In [145]:
paises_infectados = np.array([44, 550, 668, 1555, 12000])

In [146]:
paises_infectados_manana = paises_infectados * 1.20

In [147]:
paises_infectados_manana

array([   52.8,   660. ,   801.6,  1866. , 14400. ])

In [148]:
b

array([[3, 1, 8],
       [2, 8, 5],
       [4, 1, 6]])

In [149]:
b == 3

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [150]:
b < 10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [151]:
(b < 10).all()

True

In [152]:
(b < 9).all()

True

In [153]:
(b < 9).any()

True

In [154]:
(b < 0).any()

False

In [155]:
b = np.random.randint(0, 10, (5, 5))

In [156]:
b2 = np.random.randint(0, 10, (5, 5))

In [157]:
b

array([[4, 0, 7, 5, 6],
       [7, 1, 8, 6, 1],
       [0, 9, 2, 0, 3],
       [1, 8, 6, 3, 3],
       [8, 8, 6, 9, 4]])

In [158]:
b2

array([[7, 9, 2, 9, 9],
       [5, 6, 2, 1, 6],
       [2, 5, 5, 4, 7],
       [3, 7, 9, 2, 1],
       [4, 7, 6, 4, 4]])

In [159]:
b == 3

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False,  True,  True],
       [False, False, False, False, False]])

In [160]:
b == b2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False,  True]])

In [161]:
b < b2

array([[ True,  True, False,  True,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True, False, False],
       [False, False, False, False, False]])

## Broadcasting

Obtained from [link](https://cs231n.github.io/python-numpy-tutorial/#numpy)

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 

Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix.

1. We can do it *manually*, NOT making use of broadcasting

In [162]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

think of rows as shirt, hat, trousers, boots  
think of columns as Monday Tuesday Wednesday

In [163]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [164]:
v = np.array([1, 0, 1])

In [165]:
v

array([1, 0, 1])

In [166]:
# create array same dimension as x
y = np.zeros(x.shape)   

In [167]:
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [168]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    print(i)
    y[i, :] = x[i, :] + v

0
1
2
3


In [169]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [170]:
y

array([[ 2.,  2.,  4.],
       [ 5.,  5.,  7.],
       [ 8.,  8., 10.],
       [11., 11., 13.]])

2. With the use of broadcasting

In [171]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [172]:
v

array([1, 0, 1])

In [173]:
# add v to each row of x using broadcasting
y2 = x + v  

In [174]:
y2

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [175]:
y == y2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [176]:
(y == y2).all()

True

In [177]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [178]:
x.shape

(4, 3)

In [179]:
v.shape

(3,)

In [180]:
v2 = np.array([1, 2, 3, 4])

In [181]:
v2

array([1, 2, 3, 4])

In [182]:
v2.shape

(4,)

In [183]:
x + v2

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [184]:
v3 = v2.reshape(4, 1)
v3

array([[1],
       [2],
       [3],
       [4]])

In [185]:
x + v3

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

**Example**: how much do products prices deviate from the mean?

In [186]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [187]:
# mean by day
x.mean(axis=0)

array([5.5, 6.5, 7.5])

In [188]:
x - x.mean(axis=0)

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

3 dimensions: 2 shops, 4 products, 3 days

In [190]:
c = np.random.randint(0, 100, (2, 4, 3))

In [191]:
c

array([[[40,  1, 43],
        [ 4, 52, 16],
        [58, 28, 54],
        [45, 54, 66]],

       [[83, 14,  3],
        [39, 86,  6],
        [40, 37, 71],
        [ 3, 89,  5]]])

In [192]:
c.mean(axis=0)

array([[61.5,  7.5, 23. ],
       [21.5, 69. , 11. ],
       [49. , 32.5, 62.5],
       [24. , 71.5, 35.5]])

In [193]:
c.mean(axis=1)

array([[36.75, 33.75, 44.75],
       [41.25, 56.5 , 21.25]])

In [194]:
c.mean(axis=2)

array([[28.        , 24.        , 46.66666667, 55.        ],
       [33.33333333, 43.66666667, 49.33333333, 32.33333333]])

## Further materials

[NumPy Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)